In [2]:
import sys
from pathlib import Path

# Get the main project folder
PROJECT_ROOT = Path.cwd().parent

# Add project root to Python's import path
sys.path.insert(0, str(PROJECT_ROOT))

print("Project root:")
print(PROJECT_ROOT)

print("\nPython executable:")
print(sys.executable)

Project root:
d:\Projects\smart-campus-food

Python executable:
d:\Projects\smart-campus-food\venv\Scripts\python.exe

In [3]:
import pandas as pd

from src.features import (
    add_calendar_features,
    add_demand_lags
)

df = pd.read_csv(
    "../data/processed/clean_meal_data.csv"
)

df["date"] = pd.to_datetime(df["date"])

df = add_calendar_features(df)

df = add_demand_lags(df)

df.head(20)

,date,mess_name,meal_type,menu_name,hostel_occupancy_pct,exam_day,holiday,special_event,temperature_c,rainfall_mm,...,day_of_week_num,month,is_weekend,semester,portion_kg,planned_preparation_kg,waste_rate,lag_1,lag_7,rolling_7_demand
0,2025-01-01,Academic Block Mess,Breakfast,Sandwich,85.62,0,0,0,28.81,0.08,...,2,1,0,4,0.3,109.512,0.168035,NaN,NaN,NaN
18,2025-01-02,Academic Block Mess,Breakfast,Upma,79.64,0,0,0,24.86,5.04,...,3,1,0,4,0.3,102.384,0.142843,317.0,NaN,NaN
36,2025-01-03,Academic Block Mess,Breakfast,Upma,96.73,0,0,0,30.46,0.14,...,4,1,0,4,0.3,111.132,0.235564,300.0,NaN,NaN
54,2025-01-04,Academic Block Mess,Breakfast,Idli_Dosa,88.05,0,0,0,25.48,2.40,...,5,1,1,4,0.3,89.100,0.175298,313.0,NaN,NaN
72,2025-01-05,Academic Block Mess,Breakfast,Idli_Dosa,84.31,0,0,0,27.62,7.11,...,6,1,1,4,0.3,97.200,0.179950,260.0,NaN,NaN
90,2025-01-06,Academic Block Mess,Breakfast,Sandwich,89.09,0,0,0,26.22,0.00,...,0,1,0,4,0.3,117.612,0.138105,294.0,NaN,NaN
108,2025-01-07,Academic Block Mess,Breakfast,Poha,76.07,0,0,0,27.68,3.44,...,1,1,0,4,0.3,111.456,0.183459,340.0,NaN,NaN
126,2025-01-08,Academic Block Mess,Breakfast,Paratha,85.34,0,0,0,24.85,0.00,...,2,1,0,4,0.3,130.896,0.166719,317.0,317.0,305.857143
144,2025-01-09,Academic Block Mess,Breakfast,Sandwich,84.34,1,0,0,24.04,0.26,...,3,1,0,4,0.3,101.412,0.158095,364.0,300.0,312.571429
162,2025-01-10,Academic Block Mess,Breakfast,Poha,87.93,0,0,0,26.17,3.34,...,4,1,0,4,0.3,112.104,0.187889,298.0,313.0,312.285714
180,2025-01-11,Academic Block Mess,Breakfast,Sandwich,81.24,0,0,0,29.06,0.00,...,5,1,1,4,0.3,87.480,0.116051,321.0,260.0,313.428571
198,2025-01-12,Academic Block Mess,Breakfast,Paratha,83.13,0,0,0,29.05,0.00,...,6,1,1,4,0.3,97.524,0.245521,266.0,294.0,314.285714
216,2025-01-13,Academic Block Mess,Breakfast,Sandwich,83.63,0,0,0,28.74,0.00,...,0,1,0,4,0.3,111.456,0.185035,274.0,340.0,311.428571
234,2025-01-14,Academic Block Mess,Breakfast,Sandwich,90.64,0,0,0,29.21,1.09,...,1,1,0,4,0.3,111.456,0.179532,319.0,317.0,308.428571
252,2025-01-15,Academic Block Mess,Breakfast,Sandwich,87.33,0,0,0,24.20,2.19,...,2,1,0,4,0.3,113.076,0.086717,338.0,364.0,311.428571
270,2025-01-16,Academic Block Mess,Breakfast,Paratha,74.01,0,1,0,32.26,0.22,...,3,1,0,4,0.3,65.772,0.136253,344.0,298.0,308.571429
288,2025-01-17,Academic Block Mess,Breakfast,Idli_Dosa,81.33,0,0,0,27.91,0.11,...,4,1,0,4,0.3,118.584,0.158520,200.0,321.0,294.571429
306,2025-01-18,Academic Block Mess,Breakfast,Upma,89.07,0,0,0,26.22,0.00,...,5,1,1,4,0.3,83.592,0.111459,336.0,266.0,296.714286
324,2025-01-19,Academic Block Mess,Breakfast,Sandwich,81.34,0,0,0,28.74,0.23,...,6,1,1,4,0.3,86.508,0.181246,253.0,274.0,294.857143
342,2025-01-20,Academic Block Mess,Breakfast,Idli_Dosa,85.42,0,0,0,28.55,0.00,...,0,1,0,4,0.3,123.444,0.142811,248.0,319.0,291.142857

In [4]:
df[
    [
        "date",
        "mess_name",
        "meal_type",
        "students_present",
        "lag_1",
        "lag_7",
        "rolling_7_demand"
    ]
].head(20)

,date,mess_name,meal_type,students_present,lag_1,lag_7,rolling_7_demand
0,2025-01-01,Academic Block Mess,Breakfast,317,NaN,NaN,NaN
18,2025-01-02,Academic Block Mess,Breakfast,300,317.0,NaN,NaN
36,2025-01-03,Academic Block Mess,Breakfast,313,300.0,NaN,NaN
54,2025-01-04,Academic Block Mess,Breakfast,260,313.0,NaN,NaN
72,2025-01-05,Academic Block Mess,Breakfast,294,260.0,NaN,NaN
90,2025-01-06,Academic Block Mess,Breakfast,340,294.0,NaN,NaN
108,2025-01-07,Academic Block Mess,Breakfast,317,340.0,NaN,NaN
126,2025-01-08,Academic Block Mess,Breakfast,364,317.0,317.0,305.857143
144,2025-01-09,Academic Block Mess,Breakfast,298,364.0,300.0,312.571429
162,2025-01-10,Academic Block Mess,Breakfast,321,298.0,313.0,312.285714
180,2025-01-11,Academic Block Mess,Breakfast,266,321.0,260.0,313.428571
198,2025-01-12,Academic Block Mess,Breakfast,274,266.0,294.0,314.285714
216,2025-01-13,Academic Block Mess,Breakfast,319,274.0,340.0,311.428571
234,2025-01-14,Academic Block Mess,Breakfast,338,319.0,317.0,308.428571
252,2025-01-15,Academic Block Mess,Breakfast,344,338.0,364.0,311.428571
270,2025-01-16,Academic Block Mess,Breakfast,200,344.0,298.0,308.571429
288,2025-01-17,Academic Block Mess,Breakfast,336,200.0,321.0,294.571429
306,2025-01-18,Academic Block Mess,Breakfast,253,336.0,266.0,296.714286
324,2025-01-19,Academic Block Mess,Breakfast,248,253.0,274.0,294.857143
342,2025-01-20,Academic Block Mess,Breakfast,365,248.0,319.0,291.142857

In [6]:
import os

os.makedirs("../data/processed", exist_ok=True)

df.to_csv(
    "../data/processed/features.csv",
    index=False
)

print("Features saved successfully!")
print("Location: data/processed/features.csv")
print("Rows:", len(df))
print("Columns:", len(df.columns))

Features saved successfully!
Location: data/processed/features.csv
Rows: 10944
Columns: 28